export const INIT_FORUM_CATEGORY = 'INIT_FORUM_CATEGORY';
export const GET_FORUM_LIST = 'GET_FORUM_LIST';
export const GET_FORUM_SWIPER = 'GET_FORUM_SWIPER';

export const GET_SEARCH_FORUM = 'GET_SEARCH_FORUM';
export const GET_DETAIL_FORUM = 'GET_DETAIL_FORUM';
export const GET_RECOMMEND_FORUM = 'GET_RECOMMEND_FORUM';

export const SET_REPLY_FORUM = 'SET_REPLY_FORUM';
export const GET_REPLY_FORUM = 'GET_REPLY_FORUM';
export const SET_REPLY_USER_FORUM = 'SET_REPLY_USER_FORUM'
export const GET_REPLY_USER_FORUM = 'GET_REPLY_USER_FORUM';
export const REPLACE_FORUM_REPLY_USER = 'REPLACE_FORUM_REPLY_USER';
export const REPLACE_FORUM_REPLY = 'REPLACE_FORUM_REPLY';

export const FORUM_REPLY = 'FORUM_REPLY';
export const FORUM_USER_REPLY = 'FORUM_USER_REPLY';

export const GET_COLLECTION_FORUM = 'GET_COLLECTION_FORUM';
export const GET_LIKE_FORUM = 'GET_LIKE_FORUM';

export const UPDATE_FORUM_REPLY = 'UPDATE_FORUM_REPLY';
export const UPDATED_FORUM_REPLY = 'UPDATED_FORUM_REPLY';
export const ATTENTION = 'ATTENTION';