export const REPLACE_NEWS = 'REPLACE_NEWS';

export const MESSAGE_NEWSREPLY = 'MESSAGE_NEWSREPLY';
export const MESSAGE_NEWSREPLY_DELETE = 'MESSAGE_NEWSREPLY_DELETE';
export const MESSAGE_REPLY_NUMBER = 'MESSAGE_REPLY_NUMBER';
export const MESSAGE_REPLY_NUMBERDELETE = 'MESSAGE_REPLY_NUMBERDELETE';

export const MESSAGE_NEWSCOMMENT = 'MESSAGE_NEWSCOMMENT';
export const MESSAGE_NEWSCOMMENT_DELETE = 'MESSAGE_NEWSCOMMENT_DELETE';
export const MESSAGE_NEWSCOLLECTION = 'MESSAGE_NEWSCOLLECTION';
export const MESSAGE_NEWSCOLLECTION_DELETE = 'MESSAGE_NEWSCOLLECTION_DELETE';
export const MESSAGE_BULLETIN = 'MESSAGE_BULLETIN';
export const MESSAGE_NOTICE = 'MESSAGE_NOTICE';
export const MESSAGE_NOTICE_NUMBER = 'MESSAGE_NOTICE_NUMBER';
export const MESSAGE_NOTICE_DELETE = 'MESSAGE_NOTICE_DELETE';
export const MESSAGE_CONTACTUS = 'MESSAGE_CONTACTUS';


export const MESSAGE_BULLETINDETAIL = 'MESSAGE_BULLETINDETAIL';



