export const GET_TOKEN_LOGIN = 'GET_TOKEN_LOGIN';
export const GET_TOKEN_REGISTER = 'GET_TOKEN_REGISTER';
export const GET_REGISTER_AGREE = 'GET_REGISTER_AGREE';
export const GET_CODE = 'GET_CODE';
export const GET_USER = 'GET_USER';
export const IS_LOGIN = 'IS_LOGIN';
export const FONT_SIZE= 'FONT_SIZE';
export const USER_ABOUTUS= 'USER_ABOUTUS';
export const GET_FANS_USER= 'GET_FANS_USER';
export const GET_FOLLOW_USER= 'GET_FOLLOW_USER';
export const GET_DYNAMIC_USER= 'GET_DYNAMIC_USER';
export const GET_DYNAMIC_DELETE= 'GET_DYNAMIC_DELETE';

export const POST_SETTING= 'POST_SETTING';
export const GET_SETTING= 'GET_SETTING';

export const FORGET_PASSWORD = 'FORGET_PASSWORD'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

export const SIGN_OUT = 'SIGN_OUT'
export const GET_DATA_USER= 'GET_DATA_USER';

export const GET_FORUM_USER= 'GET_FORUM_USER';
export const SET_FORUM_USER= 'SET_FORUM_USER';
export const GET_PAGEDATA_USER= 'GET_PAGEDATA_USER';
export const GET_PAGEFORUM_USER= 'GET_PAGEFORUM_USER';


export const REPLACE_USER_FORUM= 'REPLACE_USER_FORUM';

export const BIND_THIRD_PARTY_ACCOUNT='BIND_THIRD_PARTY_ACCOUNT';
export const FREE_BIND_THIRD_PARTY_ACCOUNT = 'FREE_BIND_THIRD_PARTY_ACCOUNT';
export const BIND_PHONE = 'BIND_PHONE';
export const FREE_BIND_PHONE = 'FREE_BIND_PHONE';

export const HOT_SEARCH_KEYWORD = 'HOT_SEARCH_KEYWORD';
export const PLACEHOLDER_SEARCH_KEYWORD = 'PLACEHOLDER_SEARCH_KEYWORD';
export const ADD_NEWS_SEARCH_HISTORY = 'ADD_NEWS_SEARCH_HISTORY';
export const DELETE_NEWS_SEARCH_HISTORY = 'DELETE_NEWS_SEARCH_HISTORY';
export const ADD_FORUM_SEARCH_HISTORY = 'ADD_FORUM_SEARCH_HISTORY';
export const DELETE_FORUM_SEARCH_HISTORY = 'DELETE_FORUM_SEARCH_HISTORY';

export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const CHANGE_BACKGROUND = 'CHANGE_BACKGROUND';

export const SET_REPORT_OPTION = 'SET_REPORT_OPTION';

export const SET_DRAFTS = 'SET_DRAFTS';
export const ADD_DRAFTS = 'ADD_DRAFTS';
export const CHANGE_DRAFTS = 'CHANGE_DRAFTS';
export const REMOVE_DRAFTS = 'REMOVE_DRAFTS';

export const ATTENTION = 'ATTENTION';

export const GET_CODE_SHARE = 'GET_CODE_SHARE';
export const EXCHANGE_CODE = 'EXCHANGE_CODE';
export const SHARE_LIST = 'SHARE_LIST';

export const CHANGE_TINT_STATUSBAR = 'CHANGE_TINT_STATUSBAR'