export const INIT_NEWS_CATEGORY = 'INIT_NEWS_CATEGORY'

export const GET_NEWS_LIST = 'GET_NEWS_LIST';

export const GET_NEWS_SWIPER = 'GET_NEWS_SWIPER'

export const GET_DETAIL_NEWS = 'GET_DETAIL_NEWS';
export const GET_RECOMMEND_NEWS = 'GET_RECOMMEND_NEWS';
export const SET_REPLY_NEWS = 'SET_REPLY_NEWS';
export const GET_REPLY_NEWS = 'GET_REPLY_NEWS';
export const SET_REPLY_USER_NEWS = 'SET_REPLY_USER_NEWS'
export const GET_REPLY_USER_NEWS = 'GET_REPLY_USER_NEWS';
export const REPLACE_NEWS_REPLY_USER = 'REPLACE_NEWS_REPLY_USER';
export const REPLACE_NEWS_REPLY = 'REPLACE_NEWS_REPLY';
export const GET_SEARCH_NEWS = 'GET_SEARCH_NEWS';

export const NEWS_REPLY = 'NEWS_REPLY';
export const NEWS_USER_REPLY = 'NEWS_USER_REPLY';

export const GET_COLLECTION_NEWS = 'GET_COLLECTION_NEWS';

export const UPDATE_NEWS_REPLY = 'UPDATE_NEWS_REPLY';
export const UPDATED_NEWS_REPLY = 'UPDATED_NEWS_REPLY';